# This is a basic workflow to help you get started with Actions

name: Build & Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    runs-on: ubuntu-latest
    steps:
      -uses: appleboy/ssh-action@v0.1.2
      name: Build image
      with:
        host: ${{secrets.SSH_HOST}}
        key: ${{secrets.SHH_KEY}}
        username: ${{secrets.SSH_USERNAME}}
      # Runs a single command using the runners shell
        script: |
          git clone git@github.com:fdellekart/kidscamp_manager.git
          docker build .
