# This is a basic workflow to help you get started with Actions

name: Build & Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Build image
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
      # Runs a single command using the runners shell
          script: |
            docker kill $(docker ps -q)
            cd ~/app/kidscamp_manager
            git status
            git config --global user.email "florian.dellekart@hotmail.de"
            git config --global user.name "Florian Dellekart"
            git config pull.rebase false
            git checkout master
            git pull
            docker build -t kidscamp_manager_front --build-arg FIREBASE_URL=${{secrets.FIREBASE_URL}} --build-arg AUTH_URL={{secrets.AUT_URL}} --build-arg AUTH_API_KEY={{secrets.AUTH_API_KEY}} --build-arg API_URL_BROWSER={{secrets.API_URL_BROWSER}} .
            docker run -d -p 3000:3000 kidscamp_manager_front entry
